### ISSUE TITLE
[be] 주문 관련 기능 구현

### ISSUE THREAD

**Issue by yeonise** [kiosk-team-04/kiosk-max#28]
## 진행할 작업

키오스크 주문 도메인 관련 기능을 구현합니다.

## TODO

- [x] 주문 요청을 받습니다.
    - [x] 결제 방식이 `카드` 인 경우, **임의의 시간이 지난 후**에 결제가 완료됩니다.
        - [x] 결제 성공 여부는 임의로 결정합니다. _(80%의 성공률)_
        - [x] 결제에 실패한 경우 오류 메시지를 전달합니다.
    - [ ] 결제 방식이 `현금` 인 경우, 바로 결제가 완료됩니다.
        - [ ] 투입 금액이 결제 금액 미만인 경우 오류 메세지를 전달합니다.
- [x] 주문을 조회합니다.
    - [x] 결제 방식에 따른 영수증 데이터를 반환합니다.
