### ISSUE TITLE
[fe] 메뉴 담겨진 화면 UI 및 기능

### ISSUE THREAD

**Issue by lolWK** [kiosk-team-04/kiosk-max#30]
## 진행할 작업

장바구니를 구현합니다.

## TODO

- [x] 장바구니 UI
- [x] 장바구니 기능
  - [x] 담기 버튼 클릭 시 하단 담겨진 메뉴 영역 열림
  - [x] 담겨진 메뉴 영역 내부 기능
  - [x] 상호작용 없을 시 전체 취소 기능
  - [x] 결제하기 버튼 클릭 시 ‘결제선택’ 화면 열림

## 기타
같이 작업합니다
