### ISSUE TITLE
[fe] 현금 결제 UI 및 기능

### ISSUE THREAD

**Issue by lolWK** [kiosk-team-04/kiosk-max#33]
## 진행할 작업

현금 결제창 UI와 기능을 구현합니다 

## TODO

- [x] 현금 결제창 UI
- [x] 현금 결제창 기능
  - [x] 금액 버튼 클릭 시 투입 금액 증가
  - [x] 주문 금액 만큼 현금 투입 시 결제하기 버튼 활성화
