### ISSUE TITLE
[fe] 결제 방식 선택창 UI 및 기능

### ISSUE THREAD

**Issue by aaaz425** [kiosk-team-04/kiosk-max#34]
## 진행할 작업

결제 방식 선택창을 구현합니다

## TODO

- [x] 결제 방식 선택 UI
- [x] 결제 방식  선택 기능
- [x] 취소시 장바구니 표시

## 기타

카드 결제 클릭시 - 로딩 인디케이터
현금 결제 클릭시 - 현금 결제 창
