### ISSUE TITLE
[fe] 종합 결제 기능 구현

### ISSUE THREAD

**Issue by aaaz425** [kiosk-team-04/kiosk-max#38]
## 진행할 작업

현금 결제, 카드 결제의 기능을 종합적으로 구현합니다

## TODO

- [x] 현금 결제 선택 시 현금 결제 모달을 표시합니다
- [x] 카드 결제 선택 시 로딩화면을 표시합니다
- [x] 영수증 화면은 10초간 노출 되었다가 사라집니다

## 기타
