### ISSUE TITLE
[fe] 프론트엔드 리팩토링

### ISSUE THREAD

**Issue by aaaz425** [kiosk-team-04/kiosk-max#45]
## 진행할 작업

- 불필요한 코드 및 주석 제거
- 중복된 코드 통합
- css 개선
- mock 서버 데이터 추가
- prettier 및 eslint 설정 변경

## TODO

- [x] 남세 피드백 적용
- [x] 주석 제거
- [x] css 애니메이션 및 구조 변경
- [x] mock 서버 데이터 추가
- [x] prettier 및 eslint 설정 변경
